apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: vehicleapi 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vehicleapi 
    spec:
      containers:
        - name: vehicleapi 
          image: vehicle.azurecr.io/vehicleapi
          ports:
          - containerPort: 80